### ISSUE TITLE
Will this be updated to phoenix 1.7.11?

### ISSUE THREAD

**Issue by zervis** [dwyl/elixir-auth-microsoft#47]
I'm getting this error:

ArgumentError at GET /auth/microsoft/callback
no "welcome" html template defined for IntrauctionWeb.PageView  (the module does not exist)

**Comment by zervis** [comment]
Got it working by adding MicrosoftAuthHTML/MicrosoftAuthHTML.ex

`defmodule AppWeb.MicrosoftAuthHTML do
    use AppWeb, :html
  
    def welcome(assigns) do
      ~H"""
      <section class="phx-hero">
        <h1> Welcome <%= @profile.displayName %>!</h1>
        <p> You are <strong>signed in</strong>
        with your <strong>Microsoft Account</strong> <br />
        <strong style="color:teal;"><%= @profile.userPrincipalName %></strong>
        </p>
        <a href={@logout_microsoft_url}>
        <button type="button" class="rounded-md bg-indigo-50 px-3.5 py-2.5 text-sm font-semibold text-indigo-600 shadow-sm hover:bg-indigo-100">Sign Out</button>
      </a>
      </section>
      """
    end
  end`

Now I'm getting this:

Welcome Test Name!
You are signed in with your Microsoft Account
testemail@hotmail.com


User.Read is granted. 

What's wrong?

**Comment by zervis** [comment]
Got it working. I've copied httpoison_mock true to dev...

**Comment by LuchoTurtle** [comment]
Setting `httpoison_mock` to `true` is only meant to test your application, since it will make the package return predictable and successful results. It's not meant to add in your production configuration file.

Are you having trouble running the demo? Or are you having trouble using the package with `Phoenix 1.7.11`? There shouldn't be any issues at all, since we have our dependencies requirements set to the next major version.

**Comment by LuchoTurtle** [comment]
Closing this off for lack of detail. Will open again if it stops working :)
